backend:
  name: github
  repo: andrewsrichardson/food-blog
media_folder: "static/assets/"
public_folder: "/assets"
collections:
  - name: blog
    label: Blog
    create: true
    folder: src/pages/blog
    path: "{{path}}/{{path}}"
    media_folder: ""
    public_folder: ""
    fields:
      - name: "path"
        label: "Path"
        pattern:
          [
            "^[a-z0-9-]*$",
            "Must begin with a forward slash (/), and contain hyphens (-) rather than spaces. This the end of the URL to this blog post.",
          ]
      - name: "date"
        label: "Date"
        widget: "datetime"
      - name: "title"
        label: "Title"
      - name: "description"
        label: "description"
        widget: "text"
      - name: "pro-tip"
        label: "Pro Tip"
        widget: "text"
        required: false
              - name: "time"
        label: "Time to Cook"
        widget: "select"
        options:
        - { label:  "5 Mins", value: "5"}
        - { label:  "10 Mins", value: "10"}
        - { label:  "15 Mins", value: "15"}
        - { label:  "20 Mins", value: "20"}
        - { label:  "25 Mins", value: "25"}
        - { label:  "30 Mins", value: "30"}
        - { label:  "45 Mins", value: "45"}
        - { label:  "1 Hour", value: "60"}
        - { label:  "2 Hours +", value: "120"}
        required: false
      - name: "ingredients"
        label: "ingredients"
        widget: "list"
        field: { label: Ingredient, name: ingredient, widget: text }
      - name: "method"
        label: "Method"
        widget: "list"
        field: { label: Instruction, name: instruction, widget: text }
      - name: "tags"
        label: "Tags"
        widget: "select"
        multiple: true
        min: 1
        max: 3
        options:
          [
            "Breakfast",
            "Lunch",
            "Dinner",
            "Snacks",
            "Indian",
            "Italian",
            "British",
          ]
        default: ["Dinner"]
      - name: "body"
        label: "Body"
        widget: "markdown"
      - name: "main_image"
        label: "Main Image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - name: "ingredients_image"
        label: "Ingredients Image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - name: "other_images"
        label: "Other Images"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: true
