backend:
  name: github
  repo: andrewsrichardson/food-blog
media_folder: "static/assets/"
public_folder: "/assets"
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    label_singular: "blog"
    # path: "/{{path}}/index"
    # media_folder: ""
    # public_folder: ""
    fields:
      - name: "path"
        label: "Path"
        pattern:
          [
            "^[/]+[a-z0-9-]*$",
            "Must begin with a forward slash (/), and contain hyphens (-) rather than spaces. This the end of the URL to this blog post.",
          ]
      - name: "date"
        label: "Date"
        widget: "datetime"
      - name: "title"
        label: "Title"
      - name: "tags"
        label: "Tags"
        widget: "select"
        multiple: true
        min: 1
        max: 3
        options:
          [
            "Breakfast",
            "Lunch",
            "Dinner",
            "Snacks",
            "Indian",
            "Italian",
            "British",
          ]
        default: ["Dinner"]
      - name: "body"
        label: "Body"
        widget: "markdown"
      - name: "main_image"
        label: "Main Image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - name: "ingredients_image"
        label: "Ingredients Image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - name: "other_images"
        label: "Other Images"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: true
