backend:
  name: github
  repo: andrewsrichardson/food-blog
media_folder: src/images
public_folder: src/images
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: {{path}}
    fields:
      - name: "path"
        label: "Path"
        pattern: ["^[/]+[a-z0-9-]*$", "Must begin with a forward slash (/), and contain hyphens (-) rather than spaces. This the end of the URL to this blog post."]
      - name: "date"
        label: "Date"
        widget: "datetime"
      - name: "title"
        label: "Title"
      - name: "body"
        label: "Body"
        widget: "markdown"
      - name: "main-image"
        label: "Main Image"
        widget: "image"
        media_library: 
          config: 
            multiple: false
      - name: "ingredients-image"
        label: "Ingredients Image"
        widget: "image"
        media_library: 
          config: 
            multiple: false
      - name: "other-images"
        label: "Other Images"
        widget: "image"
        required: false 
        media_library:
          config: 
            multiple: true
